name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/socket_chat:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Ensure Docker is running and accessible
        run: |
          sudo systemctl start docker
          sudo chmod 666 /var/run/docker.sock  

      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/socket_chat:latest

      - name: Stop and remove old container
        run: |
          docker stop socket_chat || true
          docker rm socket_chat || true

      - name: Run Docker Container 
        run: docker run -d -p 8800:8800 --name socket_chat ${{ secrets.DOCKER_USERNAME }}/socket_chat:latest
